### PR TITLE
refactor: corrects the writing of media requests

### LINKED ISSUE #40: Refactor: Using two types of media queries
**Describe the bug**
Two ways of writing media queries are used, which contradicts the rules for writing them specified in [readme.md](https://github.com/p-foundation/pink-app/blob/main/blocks/README.md)

**To Reproduce**
1. Go to the `blocks` folder
2. Click on the style files of the blocks and their elements
3. You can see different usage of media queries.

**Desktop:**
 - OS: **iOS**
 - Browser: **Microsoft Edge**
 - Version: **116.0.1938.54**

**Additional context**
Here is how the code for media queries in some files looks now:

``` CSS
@media(max-width:1199px){
...
}

@media(max-width:659px){
...
}
```

Correct media queries should look like this:

``` CSS
@media screen and (max-width: 1199px) {
...
}

@media screen and (max-width: 659px) {
...
}
```

**Quick Instruction for Working on the Issue**
‼️ Before checking out to a new branch, ensure you have the latest updates from the main by running `git pull` command.
- **Please create a new branch**, and name it `refactor-media-queries`
- **Make Changes:** Review all stylesheet files and check them for errors in media queries, then replace them with correct ones.
- **Test thoughtfully:** Test if the media queries you've changed continue to work on all screen sizes.
- **Open a pull request:** reference the specific issue in your PR description using the following format:
`This pull request resolves [#issue_number](link_to_the_issue)`. Replace `issue_number` with the actual issue number and `link_to_the_issue` with the link to the respective issue. For example:

```bash
This pull request resolves [#123](https://github.com/username/repository/issues/123)
```

### PR DESCRIPTION
**Pull request by wwily**
## Description

This pull request resolves [#40](https://github.com/p-foundation/pink-app/issues/40)

## Changes Made

I ensured uniform usage and formatting of media queries throughout the project.

From this:

```css
@media (max-width:1199px){
...
}

@media (max-width:659px){
...
}
```

To this:

```css
@media screen and (max-width: 1199px){
...
}

@media screen and (max-width: 659px){
...
}
```

### CODE REVIEW

**Comment by naumch1k** [comment]
Hey, @NazarPauk @MarPostovik 👋
Do you guys have any rules on how to format media request cause most of those are currently written with an empty space between `max-width:` statement and a breakpoint value while those in this PR doesn't have an empty space.

```CSS
@media screen and (max-width: 659px) {}
/* vs */
@media screen and (max-width:659px) {}
```

**Comment by MarPostovik** [comment]
@naumch1k Thank you for noticing this. I think we should stick to the first option (with the space). 
@wwily  Would you kindly add the spaces to the media queries that don't have them?

**Comment by wwily** [comment]
I made changes:)

**Review by naumch1k — APPROVED** [review]
@wwily Thank you for taking the time to ensure consistent formatting in our project's media queries. Your PR has been approved!

**Pull request merged**
