### PR TITLE
fix: fixes display of image for research section for tablet version

### PR DESCRIPTION
**Pull request by MarPostovik**
## Description

This pull request resolves [#23](https://github.com/p-foundation/pink-app/issues/23)

## Changes Made

In the element `research__image` of BEM block `research` changed the `media` in tag `<source>` from `max-width: 660px` to `max-width: 1199px`

### CODE REVIEW

**Review by naumch1k — COMMENTED** [review]
Hey @Mariia, thanks a lot for addressing this issue. Your solution resolves the problem effectively!

I was wondering if there is a way we can prevent HTML from importing any images when the screen size is less than 660px. The problem now is that even though we hide the whole section with CSS on mobile devices, our app still requests an image and loads it.

Please let me know if the problem is clear 🙏 Thanks again!

**Comment by MarPostovik** [comment]
Hey @naumch1k , I think I've found the solution. I've added attribute `loading="lazy"` both for `` and `<source>`. This attribute tells browser, that image should be loaded only when it appears on screen. So, as it never appears on the screens smaller than 660px, it is never loaded on these screens. You can read [this article](https://developer.mozilla.org/ru/docs/Web/Performance/Lazy_loading) about `loading="lazy"` if you want.

**Comment by naumch1k** [comment]
@MarPostovik Wow, what a brilliant idea! 😍 Your solution using the lazy loading technique is elegant and effectively addresses the problem!

I have a small suggestion here. Since lazy loading is applied to the `` tag, there's no need to duplicate it on the `<source>` tag. Similar to attributes like `alt` and `class`, specifying it once on the `` tag suffices and automatically applies to the associated `<source>` tag.

I tested this solution by removing the `loading="lazy"` attribute from the `<source>` tag, and it works perfectly across different browsers - Chrome, Safari, and Firefox.

After you've done that, we will all be good to merge 😉

Once again, outstanding job!

**Comment by MarPostovik** [comment]
Done ✅

**Review by naumch1k — APPROVED** [review]
👍 Approved! Great job, @MarPostovik !

**Pull request merged**
